#!/usr/bin/env bash
# sync-branch-invariants.sh — Deploy branch-invariants.yml caller to all repos.
#
# `assert-branch-invariants.yml` is a reusable workflow_call in this repo
# (greenticai/.github). Without per-repo callers it never fires. This script
# generates the static 7-line caller in each repo's
# `.github/workflows/branch-invariants.yml` and opens a PR.
#
# Phase D caller fanout (plans/binary-bifurcation.md). The caller content is
# identical across every repo — no manifest-driven interpolation. Mirrors
# sync-dev-publish.sh's structure but is much smaller.
#
# Why deploy fleet-wide (not just binary-bifurcated repos):
#   The main-lane FAIL ("no `*-dev.*` version suffix on main") is universally
#   useful. Any repo that publishes to crates.io is at risk of a misconfigured
#   weekly-stable-prepare or stray dev-publish leaking a pre-release version
#   to main. The script's develop-lane WARN is a no-op on library-only repos
#   (the script returns "not binary-bifurcated, no checks"), so the wide
#   deployment costs nothing extra.
#
# Usage (from the workspace root, one level above the .github checkout):
#   bash .github/scripts/sync-branch-invariants.sh             # PR to main
#   bash .github/scripts/sync-branch-invariants.sh --dry-run   # show plan, change nothing
#   bash .github/scripts/sync-branch-invariants.sh --check     # exit non-zero on drift (CI)
#   bash .github/scripts/sync-branch-invariants.sh --repo NAME # single repo
#   bash .github/scripts/sync-branch-invariants.sh --target develop  # PR to develop instead
#
# Target branch defaults to `main` because:
#   1. The guardrail's primary purpose is rejecting `-dev` leakage onto main —
#      faster coverage there matters most.
#   2. Forward-port (Tuesday cycle) carries the file to develop within a week.
#   3. Workflow YAML adds are low-risk, fitting normal main-PR workflow.
# Override with --target develop to use the sync-dev-publish.sh pattern.
#
# Requires: gh (GitHub CLI), git, python3.
#
# Idempotent: re-running on an up-to-date repo is a no-op (counts as
# `up_to_date`). Re-runs on a repo with an open sync PR force-push the branch.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="${WORKSPACE:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
BIZ_DIR="${BIZ_DIR:-$WORKSPACE/GREENTIC-BIZ}"
CANONICAL_DIR="$WORKSPACE/.github/toolchain"
MANIFEST="$CANONICAL_DIR/REPO_MANIFEST.toml"

declare -A ORG_DIRS=(
  [greenticai]="$WORKSPACE"
  [greentic-biz]="$BIZ_DIR"
)

MODE="pr"            # pr | dry-run | check
SINGLE_REPO=""
TARGET_BRANCH="main"
SYNC_BRANCH="chore/wire-branch-invariants"
COMMIT_MSG="chore(ci): wire branch-invariants reusable into this repo"
WORKFLOW_PATH=".github/workflows/branch-invariants.yml"

shift_next=""
for arg in "$@"; do
  case "$arg" in
    --dry-run) MODE="dry-run" ;;
    --check)   MODE="check" ;;
    --repo)    shift_next="repo"; continue ;;
    --target)  shift_next="target"; continue ;;
    --help|-h)
      sed -n '2,40p' "$0"
      exit 0
      ;;
    *)
      if [[ "${shift_next:-}" == "repo" ]]; then
        SINGLE_REPO="$arg"; shift_next=""
      elif [[ "${shift_next:-}" == "target" ]]; then
        TARGET_BRANCH="$arg"; shift_next=""
      else
        echo "Unknown argument: $arg" >&2; exit 1
      fi
      ;;
  esac
done

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

synced=0
up_to_date=0
skipped=0
drifted=0
failed=0
declare -a failed_repos=()
declare -a drifted_repos=()

log_ok()    { echo -e "  ${GREEN}✓${RESET} $1"; }
log_skip()  { echo -e "  ${YELLOW}⊘${RESET} $1"; }
log_fail()  { echo -e "  ${RED}✗${RESET} $1"; }
log_info()  { echo -e "  ${BLUE}→${RESET} $1"; }
log_drift() { echo -e "  ${YELLOW}⚠${RESET} $1"; }

# Static caller content — identical across every repo. NO interpolation.
# `lane` resolves to:
#   - on push:         github.base_ref empty → falls through to ref_name (pushed branch)
#   - on pull_request: github.base_ref is the PR target (main or develop)
# The reusable workflow's job-level `if:` skips when lane is anything other
# than main or develop, so feature-branch pushes (filtered by `branches:`
# already, but doubly-defended) are no-ops.
generate_caller() {
  cat <<'EOF'
# Auto-generated by sync-branch-invariants.sh — do not edit manually.
# Wires this repo into the centralized assert-branch-invariants reusable
# in greenticai/.github (Phase D of plans/binary-bifurcation.md).
name: Branch Invariants

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  assert:
    uses: greenticai/.github/.github/workflows/assert-branch-invariants.yml@main
    with:
      lane: ${{ github.base_ref || github.ref_name }}
EOF
}

# ── Parse manifest — emit "org\trepo_name" for non-archived repos ─
parse_manifest() {
  python3 -c "
import tomllib
with open('$MANIFEST', 'rb') as f:
    m = tomllib.load(f)
for name, e in m.get('repos', {}).items():
    if e.get('archived', False):
        continue
    print(f\"{e['org']}\t{name}\")
" | sort -t$'\t' -k2,2
}

sync_repo() {
  local org="$1"
  local repo_name="$2"
  local local_dir="${ORG_DIRS[$org]:-}"

  if [[ -z "$local_dir" ]]; then
    log_skip "Unknown org: $org"
    ((skipped++)) || true
    return 0
  fi

  local repo_path="$local_dir/$repo_name"

  if [[ ! -d "$repo_path/.git" ]]; then
    log_skip "Not cloned locally"
    ((skipped++)) || true
    return 0
  fi

  if ! git -C "$repo_path" fetch origin --quiet 2>/dev/null; then
    log_fail "Failed to fetch origin"
    failed_repos+=("$repo_name (fetch)")
    ((failed++)) || true
    return 0
  fi

  if ! git -C "$repo_path" rev-parse --verify "refs/remotes/origin/$TARGET_BRANCH" >/dev/null 2>&1; then
    log_skip "No '$TARGET_BRANCH' branch on remote"
    ((skipped++)) || true
    return 0
  fi

  local expected
  expected=$(generate_caller)

  local current
  current=$(git -C "$repo_path" show "origin/$TARGET_BRANCH:$WORKFLOW_PATH" 2>/dev/null || echo "")

  if [[ "$current" == "$expected" ]]; then
    log_ok "Up to date"
    ((up_to_date++)) || true
    return 0
  fi

  local action="create"
  [[ -n "$current" ]] && action="update"

  if [[ "$MODE" == "check" ]]; then
    log_drift "Drift detected ($action $WORKFLOW_PATH)"
    drifted_repos+=("$org/$repo_name")
    ((drifted++)) || true
    return 0
  fi

  if [[ "$MODE" == "dry-run" ]]; then
    log_info "Would $action $WORKFLOW_PATH (target: $TARGET_BRANCH)"
    ((synced++)) || true
    return 0
  fi

  if ! git -C "$repo_path" diff --quiet 2>/dev/null || ! git -C "$repo_path" diff --cached --quiet 2>/dev/null; then
    log_fail "Dirty working tree — skipping"
    failed_repos+=("$repo_name (dirty)")
    ((failed++)) || true
    return 0
  fi

  local original_branch
  original_branch=$(git -C "$repo_path" branch --show-current 2>/dev/null || echo "")

  git -C "$repo_path" branch -D "$SYNC_BRANCH" 2>/dev/null || true

  if ! git -C "$repo_path" checkout -b "$SYNC_BRANCH" "origin/$TARGET_BRANCH" --quiet 2>/dev/null; then
    log_fail "Cannot create branch from origin/$TARGET_BRANCH"
    failed_repos+=("$repo_name (branch)")
    ((failed++)) || true
    [[ -n "$original_branch" ]] && git -C "$repo_path" checkout "$original_branch" --quiet 2>/dev/null || true
    return 0
  fi

  mkdir -p "$repo_path/.github/workflows"
  echo "$expected" > "$repo_path/$WORKFLOW_PATH"

  git -C "$repo_path" add "$WORKFLOW_PATH"
  if git -C "$repo_path" diff --cached --quiet 2>/dev/null; then
    log_ok "Up to date (no diff after write)"
    ((up_to_date++)) || true
    [[ -n "$original_branch" ]] && git -C "$repo_path" checkout "$original_branch" --quiet 2>/dev/null || true
    return 0
  fi

  git -C "$repo_path" commit -m "$COMMIT_MSG" --quiet

  if ! git -C "$repo_path" push origin "$SYNC_BRANCH" --force-with-lease --quiet 2>/dev/null; then
    log_fail "Push failed"
    failed_repos+=("$repo_name (push)")
    ((failed++)) || true
    [[ -n "$original_branch" ]] && git -C "$repo_path" checkout "$original_branch" --quiet 2>/dev/null || true
    return 0
  fi

  local pr_body
  pr_body=$(cat <<EOF
Wires this repo into the central \`assert-branch-invariants.yml\` reusable
workflow in \`greenticai/.github\` (Phase D of \`plans/binary-bifurcation.md\`).

The reusable already merged via \`greenticai/.github#146\`. Without this
caller it never fires in this repo.

**What it does:**

- On push or PR to \`main\`: **FAIL** if any \`Cargo.toml\` has a \`-dev.*\`
  version suffix (\`[package].version\` or \`[workspace.package].version\`)
  or \`[package].name\` matches a \`<base>-dev\` alias declared in
  \`REPO_MANIFEST.toml\`'s \`binary-crates\`.
- On push or PR to \`develop\`: **WARN** (non-fatal) if a binary-bifurcated
  repo's tree is missing an expected base name or has a \`-dev\` alias
  committed by mistake.

For library-only repos (this repo's case if not in \`binary-crates\`) the
develop-lane check is a no-op — the script reports \"not binary-bifurcated,
no checks\" and exits 0. The main-lane FAIL still applies, which is the
universal benefit.

Source: [sync-branch-invariants.sh](https://github.com/greenticai/.github/blob/main/scripts/sync-branch-invariants.sh)
EOF
)

  local pr_url
  pr_url=$(gh pr create \
    --repo "$org/$repo_name" \
    --base "$TARGET_BRANCH" \
    --head "$SYNC_BRANCH" \
    --title "$COMMIT_MSG" \
    --body "$pr_body" 2>/dev/null || echo "")

  if [[ -n "$pr_url" ]]; then
    log_ok "Synced → PR: $pr_url"
  else
    local existing
    existing=$(gh pr list --repo "$org/$repo_name" --head "$SYNC_BRANCH" --base "$TARGET_BRANCH" --json url --jq '.[0].url' 2>/dev/null || echo "")
    if [[ -n "$existing" ]]; then
      log_ok "Synced → PR (updated): $existing"
    else
      log_ok "Synced & pushed (PR creation failed — create manually)"
    fi
  fi

  ((synced++)) || true

  [[ -n "$original_branch" ]] && git -C "$repo_path" checkout "$original_branch" --quiet 2>/dev/null || true
}

# ── Main ──────────────────────────────────────────────────────────

echo -e "${BOLD}Greentic Branch-Invariants Sync${RESET}"
echo -e "Target branch: $TARGET_BRANCH"
echo -e "Mode: $MODE"
[[ -n "$SINGLE_REPO" ]] && echo -e "Single repo: $SINGLE_REPO"
echo ""

if [[ ! -f "$MANIFEST" ]]; then
  echo -e "${RED}Missing manifest: $MANIFEST${RESET}" >&2
  exit 1
fi

while IFS=$'\t' read -r org repo_name; do
  if [[ -n "$SINGLE_REPO" && "$repo_name" != "$SINGLE_REPO" ]]; then
    continue
  fi
  echo -e "${CYAN}${BOLD}[$org/$repo_name]${RESET}"
  sync_repo "$org" "$repo_name"
done < <(parse_manifest)

echo ""
echo -e "${BOLD}━━━ Summary ━━━${RESET}"
echo -e "  ${GREEN}Synced:${RESET}       $synced"
echo -e "  ${GREEN}Up to date:${RESET}   $up_to_date"
[[ "$skipped" -gt 0 ]]  && echo -e "  ${YELLOW}Skipped:${RESET}      $skipped"
[[ "$drifted" -gt 0 ]]  && echo -e "  ${YELLOW}Drifted:${RESET}      $drifted"
[[ "$failed" -gt 0 ]]   && echo -e "  ${RED}Failed:${RESET}       $failed"

if [[ ${#failed_repos[@]} -gt 0 ]]; then
  echo ""
  echo -e "  ${RED}Failed repos:${RESET}"
  for r in "${failed_repos[@]}"; do
    echo -e "    ${RED}•${RESET} $r"
  done
fi

if [[ ${#drifted_repos[@]} -gt 0 ]]; then
  echo ""
  echo -e "  ${YELLOW}Drifted repos:${RESET}"
  for r in "${drifted_repos[@]}"; do
    echo -e "    ${YELLOW}•${RESET} $r"
  done
fi

echo ""

if [[ "$MODE" == "check" && "$drifted" -gt 0 ]]; then
  exit 1
fi
exit "$failed"
